latex_labels:
  label_QCD: QCD
  label_Hbb: $H(\rightarrow b\bar{b})$
  label_Hcc: $H(\rightarrow c\bar{c})$
  label_Hgg: $H(\rightarrow gg)$
  label_H4q: $H(\rightarrow 4q)$
  label_Hqql: $H(\rightarrow l \nu qq')$
  label_Zqq: $Z(\rightarrow q\bar{q})$
  label_Wqq: $W(\rightarrow q\bar{q})$
  label_Tbqq: $t(\rightarrow b qq')$
  label_Tbl: $t(\rightarrow b l \nu)$
