_target_: src.models.flow_matching_module.SetFlowMatchingLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.00005

scheduler:
  _target_: src.schedulers.lr_scheduler.CosineWarmupScheduler
  _partial_: true
  warmup: 5
  max_iters: 10
