_target_: src.models.flow_matching_module.SetFlowMatchingLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.00005

#scheduler:
# _target_: CosineWarmupScheduler
# _partial_: true
# warmup: 1000
# max_iters: 20000

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
