_target_: src.models.flow_matching_module.SetFlowMatchingLitModule

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.0001
  weight_decay: 0.0001

scheduler:
  _target_: src.schedulers.lr_scheduler.WarmupToConstant
  _partial_: true
  num_steps: 20

features: 3
n_transforms: 1
layers: 6
hidden_dim: 128
latent: 10
activation: leaky_relu
wrapper_func: weight_norm
dropout: 0.0

t_emb: cosine
frequencies: 16
t_global_cat: True
t_local_cat: False
add_time_to_input: False

loss_type: 'diffusion'
diff_config:
  max_sr: 0.999
  min_sr: 0.02
criterion: 'huber'
sigma: 1e-4

use_normaliser: False
normaliser_config:
  max_n: 2000
