_target_: src.models.part_classifier.EPiCClassifierLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  #weight_decay: 0.00005

scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  _partial_: true
  #warmup: 1000
  #max_iters: 10000


net_config:
  input_dim: 7
  equiv_layers: 6
  hid_d: 128
  latent: 16
  activation: leaky_relu
  wrapper_func: weight_norm
  dropout: 0.0
  sum_scale: 1e-2
  global_cond_dim: 0
  local_cond_dim: 0
  t_local_cat: False
  t_global_cat: False
  num_points: 128
  num_sup_sets: 1
