_target_: src.models.flow_matching_module.SetFlowMatchingLitModule

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0001

use_normaliser: true
normaliser_config:
  max_n: 2000_000
