_target_: src.models.hl_classifier.HLClassifierLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  _partial_: true
