# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.DeviceStatsMonitor.html#lightning.pytorch.callbacks.DeviceStatsMonitor

# Automatically monitors and logs device stats during training, validation and testing stage.
# DeviceStatsMonitor is a special callback as it requires a logger to passed as argument to the Trainer.
# Look at the above link for more detailed information.
device_stats_monitor:
  _target_: pytorch_lightning.callbacks.DeviceStatsMonitor
  cpu_stats: null # if None, it will log CPU stats only if the accelerator is CPU. If True, it will log CPU stats regardless of the accelerator. If False, it will not log CPU stats regardless of the accelerator.
