# Average moving average of weights
ema:
  _target_: src.callbacks.ema.EMA
  decay: 0.9999
  apply_ema_every_n_steps: 1
  start_step: 0
  save_ema_weights_in_callback_state: true
  evaluate_ema_weights_instead: true
