# Generate data, calculate plots and metrics and log them to the logger
gen_challenge_eval:
  _target_: src.callbacks.gen_challenge.gen_challenge_eval.GenChallengeEvaluationCallback
  every_n_epochs: 100 # evaluate every n epochs
  num_jet_samples: -1 # jet samples to generate
  image_path: ${paths.log_dir}callback_logs/
  model_name: "gen_challenge"
  use_ema: True
  log_times: True
  log_epoch_zero: True
  data_type: "val"
  generation_config:
    batch_size: 2048
    ode_solver: "midpoint"
    ode_steps: 100
    verbose: False
