# Evaluate the final model on the test set for the JetNet dataset
jetclass_eval_test:
  _target_: particle_fm.callbacks.jetclass_eval_test.JetClassTestEvaluationCallback
  use_ema: true
  dataset: "test"
  nr_checkpoint_callbacks: 0
  use_last_checkpoint: true
  ckpt_path: null
  num_jet_samples: -5
  fix_seed: true
  evaluate_substructure: true
  suffix: ""
  # cond_path: ${paths.root_dir}/data/conditioning.h5
  w_dist_config:
    num_eval_samples: 50_000
    num_batches: 40
  generation_config:
    batch_size: 1024
    ode_solver: "midpoint"
    ode_steps: 100
  plot_config:
    plot_efps: true
