# Generate data, calculate plots and metrics and log them to the logger
lhco_eval:
  _target_: src.callbacks.lhco_eval.JetNetEvaluationCallback
  every_n_epochs: 100 # evaluate every n epochs
  num_jet_samples: 10_000 # jet samples to generate
  image_path: ${paths.log_dir}callback_logs/
  model_name: "lhco_flow_matching"
  use_ema: True
  log_times: True
  log_epoch_zero: True
  data_type: "test"
  w_dist_config:
    num_eval_samples: 10_000
    num_batches: 40
    calculate_efps: False
  generation_config:
    batch_size: 2048
    ode_solver: "midpoint"
    ode_steps: 50
    verbose: False
  plot_config:
    plot_efps: False
