# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html#lightning.pytorch.callbacks.LearningRateMonitor

# Automatically monitor and logs learning rate for learning rate schedulers during training.
# Look at the above link for more detailed information.
lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch" # "step" or "epoch" or None
  log_momentum: False # if True, will also log the momentum value of the optimizer at each step
